spring:
  profiles:
    active: dev # 현재 활성화할 프로필

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080 # 개발 환경 포트

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 80 # 운영 환경 포트